// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBazTC6wmOzC1GnG6yFj5zBlx12o46MTkM',
    appId: '1:1015472509991:web:a7f77b738b2eb948432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    authDomain: 'ecommerce-fc421.firebaseapp.com',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
    measurementId: 'G-J9D848THC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAYIKkQt7QUT_laV-pHOwLd15Ohhx48vQ',
    appId: '1:1015472509991:android:5fd25f2eb0675a7e432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBShklLEui9EC7RujEidNJi1LbBW2ZGzzM',
    appId: '1:1015472509991:ios:22ad8aa2524f04c5432a02',
    messagingSenderId: '1015472509991',
    projectId: 'ecommerce-fc421',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
    iosClientId:
        '1015472509991-e39esmiuc36pvdgp9uagp51j1c56ktrf.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:7b67fa8db6b2840d0653ed',
    messagingSenderId: '823307041176',
    projectId: 'ecommerce-fc421',
    databaseURL: 'https://codingwitht-c6d0f-default-rtdb.firebaseio.com',
    storageBucket: 'ecommerce-fc421.firebasestorage.app',
    androidClientId:
        '823307041176-kun16mo723tugpbptbcbupndhaubv8cn.apps.googleusercontent.com',
    iosClientId:
        '823307041176-lp36pj2a155ifcmkeil3p2ch72krur3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceAdminPanel.RunnerTests',
  );
}
