name: cwt_ecommerce_admin_panel
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins: # Use this for URL Strategy without #
    sdk: flutter


  # Custom Packages
  t_overlay_notification: ^1.1.0
  t_utils: ^0.0.4



  # Utility Packages
  intl: ^0.20.2
  uuid: ^4.5.0
  lottie: ^3.3.1
  clipboard: ^0.1.3
  image_picker: ^1.1.2
  flutter_quill: ^11.4.1
  url_launcher: ^6.3.1
  flutter_dropzone: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_colorpicker: ^1.1.0
  omni_datetime_picker: ^2.0.5
  multi_select_flutter: ^4.1.3
  image_picker_web: ^4.0.0

  # Web Specific
  web: ^1.1.0
  http: ^1.2.2
  fl_chart: ^0.70.1
  universal_html: ^2.2.4

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  firebase_storage: ^12.4.0
  cloud_functions: ^5.3.0


  # Chat
  audioplayers: ^6.1.0
  audio_waveforms: ^1.0.5
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  supabase_flutter: ^2.9.0
  firebase_messaging: ^15.2.10



  #--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/images/content/
    - assets/images/animations/
    - assets/icons/payment_methods/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Urbanist
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Light.ttf
          weight: 300
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
          weight: 400
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
          weight: 500
        - asset: assets/fonts/urbanist/Urbanist-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
          weight: 800