name: tstore_ecommerce_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # Custom Packages
  t_utils: ^0.0.4


  # Utility Packages
  gap: ^3.0.1
  dio: ^5.7.0
  uuid: ^4.5.0
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.3.1 # OR RIVE
  shimmer: ^3.0.0
  logger: ^2.5.0
  flutter_quill: ^11.4.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  image_cropper: ^8.0.2
  url_launcher: ^6.3.1
  connectivity_plus: ^6.1.3
  cached_network_image: ^3.4.1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.2.0+3
  country_code_picker: ^3.1.0
  otp_text_field: ^1.1.3
  animate_do: ^2.1.0
  badges: ^3.1.2
  wakelock_plus: ^1.2.10 #Only being used in the Dummy Data Uploader to keep screen on.


  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2

  # Firebase
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_messaging: ^15.2.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  google_sign_in: ^6.2.2
  cloud_functions: ^5.3.4
  firebase_crashlytics: ^4.3.2

  # Notification
  flutter_local_notifications: ^19.1.0

  # Chat
  audioplayers: ^6.1.0
  audio_waveforms: ^1.0.5
  flutter_chat_ui: ^1.6.15
  flutter_chat_types: ^3.6.2
  path_provider: ^2.1.4


  # Payment
  flutter_paypal: ^0.2.1
  flutter_stripe: ^11.5.0
  razorpay_flutter: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true


  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/logos/
    - assets/language/
    - assets/icons/brands/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800